//// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
//import static org.junit.Assert.*;
//import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.core.IsNot.not;
//import org.openqa.selenium.By;
//import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.firefox.FirefoxDriver;
//import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.remote.RemoteWebDriver;
//import org.openqa.selenium.remote.DesiredCapabilities;
//import org.openqa.selenium.Dimension;
//import org.openqa.selenium.WebElement;
//import org.openqa.selenium.interactions.Actions;
//import org.openqa.selenium.support.ui.ExpectedConditions;
//import org.openqa.selenium.support.ui.WebDriverWait;
//import org.openqa.selenium.JavascriptExecutor;
//import org.openqa.selenium.Alert;
//import org.openqa.selenium.Keys;
//import java.util.*;
//import java.net.MalformedURLException;
//import java.net.URL;
//public class AddemployTest {
//  private WebDriver driver;
//  private Map<String, Object> vars;
//  JavascriptExecutor js;
//  @Before
//  public void setUp() {
//    driver = new ChromeDriver();
//    js = (JavascriptExecutor) driver;
//    vars = new HashMap<String, Object>();
//  }
//  @After
//  public void tearDown() {
//    driver.quit();
//  }
//  @Test
//  public void addemploy() {
//    driver.get("https://hrm.anhtester.com/erp/desk");
//    driver.manage().window().setSize(new Dimension(978, 720));
//    js.executeScript("window.scrollTo(0,200)");
//    driver.findElement(By.id("mobile-collapse")).click();
//    {
//      WebElement element = driver.findElement(By.id("mobile-collapse"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).perform();
//    }
//    {
//      WebElement element = driver.findElement(By.tagName("body"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element, 0, 0).perform();
//    }
//    driver.findElement(By.cssSelector(".pc-item:nth-child(11) .pc-mtext")).click();
//    driver.findElement(By.linkText("Add New")).click();
//    driver.findElement(By.name("first_name")).click();
//    driver.findElement(By.name("first_name")).click();
//    driver.findElement(By.name("first_name")).sendKeys("duy");
//    driver.findElement(By.name("last_name")).click();
//    driver.findElement(By.name("last_name")).sendKeys("nguyen");
//    driver.findElement(By.name("employee_id")).click();
//    driver.findElement(By.name("contact_number")).click();
//    driver.findElement(By.name("contact_number")).sendKeys("0990099887");
//    driver.findElement(By.name("email")).click();
//    driver.findElement(By.name("email")).sendKeys("duynguyen6777@mlai.oc");
//    driver.findElement(By.name("username")).click();
//    driver.findElement(By.name("username")).sendKeys("duyndt1");
//    driver.findElement(By.name("password")).click();
//    driver.findElement(By.name("password")).sendKeys("daoobb");
//    driver.findElement(By.cssSelector("#select2-office_shift_id-ty-container > .select2-selection__placeholder")).click();
//    driver.findElement(By.id("select2-role-g2-container")).click();
//    driver.findElement(By.cssSelector("#select2-department_id-container > .select2-selection__placeholder")).click();
//    driver.findElement(By.id("select2-department_id-container")).click();
//    driver.findElement(By.id("select2-designation_id-zr-container")).click();
//    driver.findElement(By.name("basic_salary")).click();
//    driver.findElement(By.name("basic_salary")).sendKeys("10000");
//    driver.findElement(By.name("hourly_rate")).click();
//    driver.findElement(By.name("hourly_rate")).sendKeys("0100");
//    driver.findElement(By.id("select2-salay_type-container")).click();
//    driver.findElement(By.cssSelector(".btn:nth-child(2) > .ladda-label")).click();
//    {
//      WebElement element = driver.findElement(By.cssSelector(".ladda-button:nth-child(2)"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).perform();
//    }
//    {
//      WebElement element = driver.findElement(By.tagName("body"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element, 0, 0).perform();
//    }
//    driver.findElement(By.name("file")).click();
//    driver.findElement(By.name("file")).sendKeys("C:\\fakepath\\wp11689644-alejandro-garnacho-wallpapers.jpg");
//    driver.findElement(By.name("file")).click();
//    driver.findElement(By.cssSelector(".btn:nth-child(2) > .ladda-label")).click();
//    js.executeScript("window.scrollTo(0,162)");
//    {
//      WebElement element = driver.findElement(By.cssSelector(".btn-icon"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).perform();
//    }
//    {
//      WebElement element = driver.findElement(By.tagName("body"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element, 0, 0).perform();
//    }
//    js.executeScript("window.scrollTo(0,163.3333282470703)");
//    {
//      WebElement element = driver.findElement(By.cssSelector(".odd:nth-child(1) span > .btn"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).perform();
//    }
//    {
//      WebElement element = driver.findElement(By.tagName("body"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element, 0, 0).perform();
//    }
//    {
//      WebElement element = driver.findElement(By.cssSelector(".even:nth-child(2) span > .btn"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).perform();
//    }
//    {
//      WebElement element = driver.findElement(By.tagName("body"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element, 0, 0).perform();
//    }
//    {
//      WebElement element = driver.findElement(By.cssSelector(".btn-icon"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).perform();
//    }
//    {
//      WebElement element = driver.findElement(By.tagName("body"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element, 0, 0).perform();
//    }
//    {
//      WebElement element = driver.findElement(By.cssSelector(".btn-icon"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).perform();
//    }
//    {
//      WebElement element = driver.findElement(By.tagName("body"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element, 0, 0).perform();
//    }
//    driver.findElement(By.cssSelector(".even:nth-child(2) > td:nth-child(4)")).click();
//  }
//}
